/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class CMMError extends java.lang.Exception {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CMMError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMMError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_CMMError(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   public String getMessage() {
      return getMsg();
   }

  public CMMError(String msg, int code) {
    this(MMCoreJJNI.new_CMMError__SWIG_0(msg, code), true);
  }

  public CMMError(String specificMsg, String coreMsg, int code) {
    this(MMCoreJJNI.new_CMMError__SWIG_1(specificMsg, coreMsg, code), true);
  }

  public CMMError(int code) {
    this(MMCoreJJNI.new_CMMError__SWIG_2(code), true);
  }

  public String getMsg() {
    return MMCoreJJNI.CMMError_getMsg(swigCPtr, this);
  }

  public int getCode() {
    return MMCoreJJNI.CMMError_getCode(swigCPtr, this);
  }

  public void setCoreMsg(String msg) {
    MMCoreJJNI.CMMError_setCoreMsg(swigCPtr, this, msg);
  }

  public String getCoreMsg() {
    return MMCoreJJNI.CMMError_getCoreMsg(swigCPtr, this);
  }

}
