/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class Configuration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Configuration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Configuration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_Configuration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Configuration() {
    this(MMCoreJJNI.new_Configuration(), true);
  }

  public void addSetting(PropertySetting setting) {
    MMCoreJJNI.Configuration_addSetting(swigCPtr, this, PropertySetting.getCPtr(setting), setting);
  }

  public void deleteSetting(String device, String prop) {
    MMCoreJJNI.Configuration_deleteSetting(swigCPtr, this, device, prop);
  }

  public boolean isPropertyIncluded(String device, String property) {
    return MMCoreJJNI.Configuration_isPropertyIncluded(swigCPtr, this, device, property);
  }

  public boolean isSettingIncluded(PropertySetting ps) {
    return MMCoreJJNI.Configuration_isSettingIncluded(swigCPtr, this, PropertySetting.getCPtr(ps), ps);
  }

  public boolean isConfigurationIncluded(Configuration cfg) {
    return MMCoreJJNI.Configuration_isConfigurationIncluded(swigCPtr, this, Configuration.getCPtr(cfg), cfg);
  }

  public PropertySetting getSetting(long index) throws java.lang.Exception {
    return new PropertySetting(MMCoreJJNI.Configuration_getSetting__SWIG_0(swigCPtr, this, index), true);
  }

  public PropertySetting getSetting(String device, String prop) {
    return new PropertySetting(MMCoreJJNI.Configuration_getSetting__SWIG_1(swigCPtr, this, device, prop), true);
  }

  public long size() {
    return MMCoreJJNI.Configuration_size(swigCPtr, this);
  }

  public String getVerbose() {
    return MMCoreJJNI.Configuration_getVerbose(swigCPtr, this);
  }

  public String Serialize() {
    return MMCoreJJNI.Configuration_Serialize(swigCPtr, this);
  }

  public void Restore(String data) {
    MMCoreJJNI.Configuration_Restore(swigCPtr, this, data);
  }

}
