/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public final class DeviceNotification {
  public final static DeviceNotification Attention = new DeviceNotification("Attention");
  public final static DeviceNotification Done = new DeviceNotification("Done");
  public final static DeviceNotification StatusChanged = new DeviceNotification("StatusChanged");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceNotification swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceNotification.class + " with value " + swigValue);
  }

  private DeviceNotification(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceNotification(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceNotification(String swigName, DeviceNotification swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceNotification[] swigValues = { Attention, Done, StatusChanged };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

