/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public final class DeviceDetectionStatus {
  public final static DeviceDetectionStatus Unimplemented = new DeviceDetectionStatus("Unimplemented", MMCoreJJNI.Unimplemented_get());
  public final static DeviceDetectionStatus Misconfigured = new DeviceDetectionStatus("Misconfigured", MMCoreJJNI.Misconfigured_get());
  public final static DeviceDetectionStatus CanNotCommunicate = new DeviceDetectionStatus("CanNotCommunicate", MMCoreJJNI.CanNotCommunicate_get());
  public final static DeviceDetectionStatus CanCommunicate = new DeviceDetectionStatus("CanCommunicate", MMCoreJJNI.CanCommunicate_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceDetectionStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceDetectionStatus.class + " with value " + swigValue);
  }

  private DeviceDetectionStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceDetectionStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceDetectionStatus(String swigName, DeviceDetectionStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceDetectionStatus[] swigValues = { Unimplemented, Misconfigured, CanNotCommunicate, CanCommunicate };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

