/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class LongVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LongVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_LongVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LongVector() {
    this(MMCoreJJNI.new_LongVector__SWIG_0(), true);
  }

  public LongVector(long n) {
    this(MMCoreJJNI.new_LongVector__SWIG_1(n), true);
  }

  public long size() {
    return MMCoreJJNI.LongVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MMCoreJJNI.LongVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MMCoreJJNI.LongVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MMCoreJJNI.LongVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MMCoreJJNI.LongVector_clear(swigCPtr, this);
  }

  public void add(int x) {
    MMCoreJJNI.LongVector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return MMCoreJJNI.LongVector_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    MMCoreJJNI.LongVector_set(swigCPtr, this, i, val);
  }

}
