/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class MetadataTag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MetadataTag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MetadataTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_MetadataTag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetDevice() {
    return MMCoreJJNI.MetadataTag_GetDevice(swigCPtr, this);
  }

  public String GetName() {
    return MMCoreJJNI.MetadataTag_GetName(swigCPtr, this);
  }

  public String GetQualifiedName() {
    return MMCoreJJNI.MetadataTag_GetQualifiedName(swigCPtr, this);
  }

  public boolean IsReadOnly() {
    return MMCoreJJNI.MetadataTag_IsReadOnly(swigCPtr, this);
  }

  public void SetDevice(String device) {
    MMCoreJJNI.MetadataTag_SetDevice(swigCPtr, this, device);
  }

  public void SetName(String name) {
    MMCoreJJNI.MetadataTag_SetName(swigCPtr, this, name);
  }

  public void SetReadOnly(boolean ro) {
    MMCoreJJNI.MetadataTag_SetReadOnly(swigCPtr, this, ro);
  }

  public MetadataSingleTag ToSingleTag() {
    long cPtr = MMCoreJJNI.MetadataTag_ToSingleTag(swigCPtr, this);
    return (cPtr == 0) ? null : new MetadataSingleTag(cPtr, false);
  }

  public MetadataArrayTag ToArrayTag() {
    long cPtr = MMCoreJJNI.MetadataTag_ToArrayTag(swigCPtr, this);
    return (cPtr == 0) ? null : new MetadataArrayTag(cPtr, false);
  }

  public MetadataTag Clone() {
    long cPtr = MMCoreJJNI.MetadataTag_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MetadataTag(cPtr, false);
  }

  public String Serialize() {
    return MMCoreJJNI.MetadataTag_Serialize(swigCPtr, this);
  }

  public boolean Restore(String stream) {
    return MMCoreJJNI.MetadataTag_Restore(swigCPtr, this, stream);
  }

}
