/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class MetadataArrayTag extends MetadataTag {
  private long swigCPtr;

  protected MetadataArrayTag(long cPtr, boolean cMemoryOwn) {
    super(MMCoreJJNI.MetadataArrayTag_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MetadataArrayTag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_MetadataArrayTag(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MetadataArrayTag() {
    this(MMCoreJJNI.new_MetadataArrayTag(), true);
  }

  public MetadataArrayTag ToArrayTag() {
    long cPtr = MMCoreJJNI.MetadataArrayTag_ToArrayTag(swigCPtr, this);
    return (cPtr == 0) ? null : new MetadataArrayTag(cPtr, false);
  }

  public void AddValue(String val) {
    MMCoreJJNI.MetadataArrayTag_AddValue(swigCPtr, this, val);
  }

  public void SetValue(String val, long idx) {
    MMCoreJJNI.MetadataArrayTag_SetValue(swigCPtr, this, val, idx);
  }

  public String GetValue(long idx) {
    return MMCoreJJNI.MetadataArrayTag_GetValue(swigCPtr, this, idx);
  }

  public long GetSize() {
    return MMCoreJJNI.MetadataArrayTag_GetSize(swigCPtr, this);
  }

  public MetadataTag Clone() {
    long cPtr = MMCoreJJNI.MetadataArrayTag_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MetadataTag(cPtr, false);
  }

  public String Serialize() {
    return MMCoreJJNI.MetadataArrayTag_Serialize(swigCPtr, this);
  }

  public boolean Restore(String stream) {
    return MMCoreJJNI.MetadataArrayTag_Restore(swigCPtr, this, stream);
  }

}
