/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class Metadata {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Metadata(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Metadata obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_Metadata(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Metadata() {
    this(MMCoreJJNI.new_Metadata__SWIG_0(), true);
  }

  public Metadata(Metadata original) {
    this(MMCoreJJNI.new_Metadata__SWIG_1(Metadata.getCPtr(original), original), true);
  }

  public void Clear() {
    MMCoreJJNI.Metadata_Clear(swigCPtr, this);
  }

  public StrVector GetKeys() {
    return new StrVector(MMCoreJJNI.Metadata_GetKeys(swigCPtr, this), true);
  }

  public boolean HasTag(String key) {
    return MMCoreJJNI.Metadata_HasTag(swigCPtr, this, key);
  }

  public MetadataSingleTag GetSingleTag(String key) throws java.lang.Exception {
    return new MetadataSingleTag(MMCoreJJNI.Metadata_GetSingleTag(swigCPtr, this, key), true);
  }

  public MetadataArrayTag GetArrayTag(String key) throws java.lang.Exception {
    return new MetadataArrayTag(MMCoreJJNI.Metadata_GetArrayTag(swigCPtr, this, key), true);
  }

  public void SetTag(MetadataTag tag) {
    MMCoreJJNI.Metadata_SetTag(swigCPtr, this, MetadataTag.getCPtr(tag), tag);
  }

  public void RemoveTag(String key) {
    MMCoreJJNI.Metadata_RemoveTag(swigCPtr, this, key);
  }

  public Metadata eql(Metadata rhs) {
    return new Metadata(MMCoreJJNI.Metadata_eql(swigCPtr, this, Metadata.getCPtr(rhs), rhs), false);
  }

  public void Merge(Metadata newTags) {
    MMCoreJJNI.Metadata_Merge(swigCPtr, this, Metadata.getCPtr(newTags), newTags);
  }

  public String Serialize() {
    return MMCoreJJNI.Metadata_Serialize(swigCPtr, this);
  }

  public String readLine(SWIGTYPE_p_std__istringstream is) {
    return MMCoreJJNI.Metadata_readLine(swigCPtr, this, SWIGTYPE_p_std__istringstream.getCPtr(is));
  }

  public boolean Restore(String stream) {
    return MMCoreJJNI.Metadata_Restore(swigCPtr, this, stream);
  }

  public String Dump() {
    return MMCoreJJNI.Metadata_Dump(swigCPtr, this);
  }

}
