/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

   import java.io.File;

   import java.util.ArrayList;
   import java.util.List;
   import java.net.URL;
   import java.net.URLDecoder;

public class MMCoreJJNI {


  private static String URLtoFilePath(URL url) throws Exception {
    // We need to get rid of multiple protocols (jar: and file:)
    // and end up with an file path correct on every platform.
    // The following lines seem to work, though it's ugly:
	String url1 = URLDecoder.decode(url.getPath(), "UTF-8");
	String url2 = URLDecoder.decode(new URL(url1).getPath(), "UTF-8");
	return new File(url2).getAbsolutePath();
  }

  private static String getJarPath() {
    String classFile = "/mmcorej/CMMCore.class";
    try {
		String path = URLtoFilePath(CMMCore.class.getResource(classFile));
		int bang = path.indexOf('!');
		if (bang > 0)
			path = path.substring(0, bang);
		System.out.println("MMCoreJ.jar path = " + path);
		return path;
	} catch (Exception e) {
		return "";
	}
  }

  private static String getPlatformString() {
    String osName = System.getProperty("os.name");
    String osArch = System.getProperty("os.arch");
    return osName.startsWith("Mac") ? "macosx" :
      (osName.startsWith("Win") ? "win" : osName.toLowerCase()) +
      (osArch.indexOf("64") < 0 ? "32" : "64");
  }

  public static void loadLibrary(List<File> searchPaths, String name) {
    String libraryName = System.mapLibraryName(name);
    for (File path : searchPaths)
        if (new File(path, libraryName).exists()) {
            System.load(new File(path, libraryName).getAbsolutePath());
            return;
        }
    System.loadLibrary(name);
  }

  static {
    List<File> searchPaths = new ArrayList<File>();
    File directory = new File(getJarPath()).getParentFile();
    searchPaths.add(directory);
    directory = directory.getParentFile();
    searchPaths.add(directory);
    String platform = getPlatformString();
    File directoryMM = new File(new File(directory, "mm"), platform);
    searchPaths.add(directoryMM);
    directory = directory.getParentFile();
    searchPaths.add(directory);
    directoryMM = new File(new File(directory, "mm"), platform);
    searchPaths.add(directoryMM);
    // on Linux use the LSB-defined library path (set in configure.common)
    if (platform.startsWith("linux"))
        searchPaths.add(new File(MMCoreJConstants.DEVICEADAPTERPATH));
    
	try {
	    loadLibrary(searchPaths, "MMCoreJ_wrap");
        for (File path : searchPaths) {
          System.out.println(path.getAbsolutePath());
          CMMCore.addSearchPath(path.getAbsolutePath());
          }
    } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library failed to load. \n" + e);
        // do not exit here, loadLibrary does not work on all platforms in the same way,
        // perhaps the library is already loaded.
        //System.exit(1);
    }
  }

  public final static native long new_CharVector__SWIG_0();
  public final static native long new_CharVector__SWIG_1(long jarg1);
  public final static native long CharVector_size(long jarg1, CharVector jarg1_);
  public final static native long CharVector_capacity(long jarg1, CharVector jarg1_);
  public final static native void CharVector_reserve(long jarg1, CharVector jarg1_, long jarg2);
  public final static native boolean CharVector_isEmpty(long jarg1, CharVector jarg1_);
  public final static native void CharVector_clear(long jarg1, CharVector jarg1_);
  public final static native void CharVector_add(long jarg1, CharVector jarg1_, char jarg2);
  public final static native char CharVector_get(long jarg1, CharVector jarg1_, int jarg2);
  public final static native void CharVector_set(long jarg1, CharVector jarg1_, int jarg2, char jarg3);
  public final static native void delete_CharVector(long jarg1);
  public final static native long new_LongVector__SWIG_0();
  public final static native long new_LongVector__SWIG_1(long jarg1);
  public final static native long LongVector_size(long jarg1, LongVector jarg1_);
  public final static native long LongVector_capacity(long jarg1, LongVector jarg1_);
  public final static native void LongVector_reserve(long jarg1, LongVector jarg1_, long jarg2);
  public final static native boolean LongVector_isEmpty(long jarg1, LongVector jarg1_);
  public final static native void LongVector_clear(long jarg1, LongVector jarg1_);
  public final static native void LongVector_add(long jarg1, LongVector jarg1_, int jarg2);
  public final static native int LongVector_get(long jarg1, LongVector jarg1_, int jarg2);
  public final static native void LongVector_set(long jarg1, LongVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_LongVector(long jarg1);
  public final static native long new_DoubleVector__SWIG_0();
  public final static native long new_DoubleVector__SWIG_1(long jarg1);
  public final static native long DoubleVector_size(long jarg1, DoubleVector jarg1_);
  public final static native long DoubleVector_capacity(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_reserve(long jarg1, DoubleVector jarg1_, long jarg2);
  public final static native boolean DoubleVector_isEmpty(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_clear(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_add(long jarg1, DoubleVector jarg1_, double jarg2);
  public final static native double DoubleVector_get(long jarg1, DoubleVector jarg1_, int jarg2);
  public final static native void DoubleVector_set(long jarg1, DoubleVector jarg1_, int jarg2, double jarg3);
  public final static native void delete_DoubleVector(long jarg1);
  public final static native long new_StrVector__SWIG_0();
  public final static native long new_StrVector__SWIG_1(long jarg1);
  public final static native long StrVector_size(long jarg1, StrVector jarg1_);
  public final static native long StrVector_capacity(long jarg1, StrVector jarg1_);
  public final static native void StrVector_reserve(long jarg1, StrVector jarg1_, long jarg2);
  public final static native boolean StrVector_isEmpty(long jarg1, StrVector jarg1_);
  public final static native void StrVector_clear(long jarg1, StrVector jarg1_);
  public final static native void StrVector_add(long jarg1, StrVector jarg1_, String jarg2);
  public final static native String StrVector_get(long jarg1, StrVector jarg1_, int jarg2);
  public final static native void StrVector_set(long jarg1, StrVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StrVector(long jarg1);
  public final static native long new_BooleanVector__SWIG_0();
  public final static native long new_BooleanVector__SWIG_1(long jarg1);
  public final static native long BooleanVector_size(long jarg1, BooleanVector jarg1_);
  public final static native long BooleanVector_capacity(long jarg1, BooleanVector jarg1_);
  public final static native void BooleanVector_reserve(long jarg1, BooleanVector jarg1_, long jarg2);
  public final static native boolean BooleanVector_isEmpty(long jarg1, BooleanVector jarg1_);
  public final static native void BooleanVector_clear(long jarg1, BooleanVector jarg1_);
  public final static native void BooleanVector_add(long jarg1, BooleanVector jarg1_, boolean jarg2);
  public final static native boolean BooleanVector_get(long jarg1, BooleanVector jarg1_, int jarg2);
  public final static native void BooleanVector_set(long jarg1, BooleanVector jarg1_, int jarg2, boolean jarg3);
  public final static native void delete_BooleanVector(long jarg1);
  public final static native long new_pair_ss__SWIG_0();
  public final static native long new_pair_ss__SWIG_1(String jarg1, String jarg2);
  public final static native long new_pair_ss__SWIG_2(long jarg1, pair_ss jarg1_);
  public final static native void pair_ss_first_set(long jarg1, pair_ss jarg1_, String jarg2);
  public final static native String pair_ss_first_get(long jarg1, pair_ss jarg1_);
  public final static native void pair_ss_second_set(long jarg1, pair_ss jarg1_, String jarg2);
  public final static native String pair_ss_second_get(long jarg1, pair_ss jarg1_);
  public final static native void delete_pair_ss(long jarg1);
  public final static native long new_StrMap__SWIG_0();
  public final static native long new_StrMap__SWIG_1(long jarg1, StrMap jarg1_);
  public final static native long StrMap_size(long jarg1, StrMap jarg1_);
  public final static native boolean StrMap_empty(long jarg1, StrMap jarg1_);
  public final static native void StrMap_clear(long jarg1, StrMap jarg1_);
  public final static native String StrMap_get(long jarg1, StrMap jarg1_, String jarg2);
  public final static native void StrMap_set(long jarg1, StrMap jarg1_, String jarg2, String jarg3);
  public final static native void StrMap_del(long jarg1, StrMap jarg1_, String jarg2);
  public final static native boolean StrMap_has_key(long jarg1, StrMap jarg1_, String jarg2);
  public final static native void delete_StrMap(long jarg1);
  public final static native int MM_CODE_OK_get();
  public final static native int MM_CODE_ERR_get();
  public final static native int DEVICE_OK_get();
  public final static native int DEVICE_ERR_get();
  public final static native int DEVICE_INVALID_PROPERTY_get();
  public final static native int DEVICE_INVALID_PROPERTY_VALUE_get();
  public final static native int DEVICE_DUPLICATE_PROPERTY_get();
  public final static native int DEVICE_INVALID_PROPERTY_TYPE_get();
  public final static native int DEVICE_NATIVE_MODULE_FAILED_get();
  public final static native int DEVICE_UNSUPPORTED_DATA_FORMAT_get();
  public final static native int DEVICE_INTERNAL_INCONSISTENCY_get();
  public final static native int DEVICE_NOT_SUPPORTED_get();
  public final static native int DEVICE_UNKNOWN_LABEL_get();
  public final static native int DEVICE_UNSUPPORTED_COMMAND_get();
  public final static native int DEVICE_UNKNOWN_POSITION_get();
  public final static native int DEVICE_NO_CALLBACK_REGISTERED_get();
  public final static native int DEVICE_SERIAL_COMMAND_FAILED_get();
  public final static native int DEVICE_SERIAL_BUFFER_OVERRUN_get();
  public final static native int DEVICE_SERIAL_INVALID_RESPONSE_get();
  public final static native int DEVICE_SERIAL_TIMEOUT_get();
  public final static native int DEVICE_SELF_REFERENCE_get();
  public final static native int DEVICE_NO_PROPERTY_DATA_get();
  public final static native int DEVICE_DUPLICATE_LABEL_get();
  public final static native int DEVICE_INVALID_INPUT_PARAM_get();
  public final static native int DEVICE_BUFFER_OVERFLOW_get();
  public final static native int DEVICE_NONEXISTENT_CHANNEL_get();
  public final static native int DEVICE_INVALID_PROPERTY_LIMTS_get();
  public final static native int DEVICE_SNAP_IMAGE_FAILED_get();
  public final static native int DEVICE_IMAGE_PARAMS_FAILED_get();
  public final static native int DEVICE_CORE_FOCUS_STAGE_UNDEF_get();
  public final static native int DEVICE_CORE_EXPOSURE_FAILED_get();
  public final static native int DEVICE_CORE_CONFIG_FAILED_get();
  public final static native int DEVICE_CAMERA_BUSY_ACQUIRING_get();
  public final static native int DEVICE_INCOMPATIBLE_IMAGE_get();
  public final static native int DEVICE_CAN_NOT_SET_PROPERTY_get();
  public final static native int DEVICE_CORE_CHANNEL_PRESETS_FAILED_get();
  public final static native int DEVICE_LOCALLY_DEFINED_ERROR_get();
  public final static native int DEVICE_NOT_CONNECTED_get();
  public final static native int DEVICE_COMM_HUB_MISSING_get();
  public final static native int DEVICE_DUPLICATE_LIBRARY_get();
  public final static native int DEVICE_PROPERTY_NOT_SEQUENCEABLE_get();
  public final static native int DEVICE_SEQUENCE_TOO_LARGE_get();
  public final static native int DEVICE_OUT_OF_MEMORY_get();
  public final static native int DEVICE_NOT_YET_IMPLEMENTED_get();
  public final static native int MaxStrLength_get();
  public final static native String g_Keyword_Name_get();
  public final static native String g_Keyword_Description_get();
  public final static native String g_Keyword_CameraName_get();
  public final static native String g_Keyword_CameraID_get();
  public final static native String g_Keyword_CameraChannelName_get();
  public final static native String g_Keyword_CameraChannelIndex_get();
  public final static native String g_Keyword_Binning_get();
  public final static native String g_Keyword_Exposure_get();
  public final static native String g_Keyword_ActualExposure_get();
  public final static native String g_Keyword_ActualInterval_ms_get();
  public final static native String g_Keyword_Interval_ms_get();
  public final static native String g_Keyword_Elapsed_Time_ms_get();
  public final static native String g_Keyword_PixelType_get();
  public final static native String g_Keyword_ReadoutTime_get();
  public final static native String g_Keyword_ReadoutMode_get();
  public final static native String g_Keyword_Gain_get();
  public final static native String g_Keyword_EMGain_get();
  public final static native String g_Keyword_Offset_get();
  public final static native String g_Keyword_CCDTemperature_get();
  public final static native String g_Keyword_CCDTemperatureSetPoint_get();
  public final static native String g_Keyword_State_get();
  public final static native String g_Keyword_Label_get();
  public final static native String g_Keyword_Position_get();
  public final static native String g_Keyword_Type_get();
  public final static native String g_Keyword_Delay_get();
  public final static native String g_Keyword_BaudRate_get();
  public final static native String g_Keyword_DataBits_get();
  public final static native String g_Keyword_StopBits_get();
  public final static native String g_Keyword_Parity_get();
  public final static native String g_Keyword_Handshaking_get();
  public final static native String g_Keyword_DelayBetweenCharsMs_get();
  public final static native String g_Keyword_Port_get();
  public final static native String g_Keyword_AnswerTimeout_get();
  public final static native String g_Keyword_Speed_get();
  public final static native String g_Keyword_CoreDevice_get();
  public final static native String g_Keyword_CoreInitialize_get();
  public final static native String g_Keyword_CoreCamera_get();
  public final static native String g_Keyword_CoreShutter_get();
  public final static native String g_Keyword_CoreXYStage_get();
  public final static native String g_Keyword_CoreFocus_get();
  public final static native String g_Keyword_CoreAutoFocus_get();
  public final static native String g_Keyword_CoreAutoShutter_get();
  public final static native String g_Keyword_CoreChannelGroup_get();
  public final static native String g_Keyword_CoreImageProcessor_get();
  public final static native String g_Keyword_CoreSLM_get();
  public final static native String g_Keyword_CoreGalvo_get();
  public final static native String g_Keyword_CoreTimeoutMs_get();
  public final static native String g_Keyword_Channel_get();
  public final static native String g_Keyword_Version_get();
  public final static native String g_Keyword_ColorMode_get();
  public final static native String g_Keyword_Transpose_SwapXY_get();
  public final static native String g_Keyword_Transpose_MirrorX_get();
  public final static native String g_Keyword_Transpose_MirrorY_get();
  public final static native String g_Keyword_Transpose_Correction_get();
  public final static native String g_Keyword_Closed_Position_get();
  public final static native String g_Keyword_HubID_get();
  public final static native String g_Keyword_Metadata_Z_get();
  public final static native String g_Keyword_Meatdata_Exposure_get();
  public final static native String g_Keyword_Metadata_Score_get();
  public final static native String g_Keyword_Metadata_ImageNumber_get();
  public final static native String g_Keyword_Metadata_StartTime_get();
  public final static native String g_Keyword_Metadata_ROI_X_get();
  public final static native String g_Keyword_Metadata_ROI_Y_get();
  public final static native String g_FieldDelimiters_get();
  public final static native String g_CFGCommand_Device_get();
  public final static native String g_CFGCommand_Label_get();
  public final static native String g_CFGCommand_Property_get();
  public final static native String g_CFGCommand_Configuration_get();
  public final static native String g_CFGCommand_ConfigGroup_get();
  public final static native String g_CFGCommand_Equipment_get();
  public final static native String g_CFGCommand_Delay_get();
  public final static native String g_CFGCommand_ImageSynchro_get();
  public final static native String g_CFGCommand_ConfigPixelSize_get();
  public final static native String g_CFGCommand_PixelSize_um_get();
  public final static native String g_CFGCommand_ParentID_get();
  public final static native String g_CFGGroup_System_get();
  public final static native String g_CFGGroup_System_Startup_get();
  public final static native String g_CFGGroup_System_Shutdown_get();
  public final static native String g_CFGGroup_PixelSizeUm_get();
  public final static native int _DATABITS_5_get();
  public final static native int _DATABITS_6_get();
  public final static native int _DATABITS_7_get();
  public final static native int _DATABITS_8_get();
  public final static native int _FLOWCONTROL_NONE_get();
  public final static native int _FLOWCONTROL_RTSCTS_IN_get();
  public final static native int _FLOWCONTROL_RTSCTS_OUT_get();
  public final static native int _FLOWCONTROL_XONXOFF_IN_get();
  public final static native int _FLOWCONTROL_XONXOFF_OUT_get();
  public final static native int _PARITY_EVEN_get();
  public final static native int _PARITY_MARK_get();
  public final static native int _PARITY_NONE_get();
  public final static native int _PARITY_ODD_get();
  public final static native int _PARITY_SPACE_get();
  public final static native int _STOPBITS_1_get();
  public final static native int _STOPBITS_1_5_get();
  public final static native int _STOPBITS_2_get();
  public final static native int UnknownType_get();
  public final static native int Unimplemented_get();
  public final static native int Misconfigured_get();
  public final static native int CanNotCommunicate_get();
  public final static native int CanCommunicate_get();
  public final static native long new_CMMError__SWIG_0(String jarg1, int jarg2);
  public final static native long new_CMMError__SWIG_1(String jarg1, String jarg2, int jarg3);
  public final static native long new_CMMError__SWIG_2(int jarg1);
  public final static native void delete_CMMError(long jarg1);
  public final static native String CMMError_getMsg(long jarg1, CMMError jarg1_);
  public final static native int CMMError_getCode(long jarg1, CMMError jarg1_);
  public final static native void CMMError_setCoreMsg(long jarg1, CMMError jarg1_, String jarg2);
  public final static native String CMMError_getCoreMsg(long jarg1, CMMError jarg1_);
  public final static native long new_PropertySetting__SWIG_0(String jarg1, String jarg2, String jarg3, boolean jarg4);
  public final static native long new_PropertySetting__SWIG_1(String jarg1, String jarg2, String jarg3);
  public final static native long new_PropertySetting__SWIG_2();
  public final static native void delete_PropertySetting(long jarg1);
  public final static native String PropertySetting_getDeviceLabel(long jarg1, PropertySetting jarg1_);
  public final static native String PropertySetting_getPropertyName(long jarg1, PropertySetting jarg1_);
  public final static native boolean PropertySetting_getReadOnly(long jarg1, PropertySetting jarg1_);
  public final static native String PropertySetting_getPropertyValue(long jarg1, PropertySetting jarg1_);
  public final static native String PropertySetting_getKey(long jarg1, PropertySetting jarg1_);
  public final static native String PropertySetting_generateKey(String jarg1, String jarg2);
  public final static native String PropertySetting_Serialize(long jarg1, PropertySetting jarg1_);
  public final static native void PropertySetting_Restore(long jarg1, PropertySetting jarg1_, String jarg2);
  public final static native String PropertySetting_getVerbose(long jarg1, PropertySetting jarg1_);
  public final static native boolean PropertySetting_isEqualTo(long jarg1, PropertySetting jarg1_, long jarg2, PropertySetting jarg2_);
  public final static native long new_PropertyPair__SWIG_0(String jarg1, String jarg2);
  public final static native long new_PropertyPair__SWIG_1();
  public final static native void delete_PropertyPair(long jarg1);
  public final static native String PropertyPair_getPropertyName(long jarg1, PropertyPair jarg1_);
  public final static native String PropertyPair_getPropertyValue(long jarg1, PropertyPair jarg1_);
  public final static native long new_Configuration();
  public final static native void delete_Configuration(long jarg1);
  public final static native void Configuration_addSetting(long jarg1, Configuration jarg1_, long jarg2, PropertySetting jarg2_);
  public final static native void Configuration_deleteSetting(long jarg1, Configuration jarg1_, String jarg2, String jarg3);
  public final static native boolean Configuration_isPropertyIncluded(long jarg1, Configuration jarg1_, String jarg2, String jarg3);
  public final static native boolean Configuration_isSettingIncluded(long jarg1, Configuration jarg1_, long jarg2, PropertySetting jarg2_);
  public final static native boolean Configuration_isConfigurationIncluded(long jarg1, Configuration jarg1_, long jarg2, Configuration jarg2_);
  public final static native long Configuration_getSetting__SWIG_0(long jarg1, Configuration jarg1_, long jarg2) throws java.lang.Exception;
  public final static native long Configuration_getSetting__SWIG_1(long jarg1, Configuration jarg1_, String jarg2, String jarg3);
  public final static native long Configuration_size(long jarg1, Configuration jarg1_);
  public final static native String Configuration_getVerbose(long jarg1, Configuration jarg1_);
  public final static native String Configuration_Serialize(long jarg1, Configuration jarg1_);
  public final static native void Configuration_Restore(long jarg1, Configuration jarg1_, String jarg2);
  public final static native long new_PropertyBlock();
  public final static native void delete_PropertyBlock(long jarg1);
  public final static native void PropertyBlock_addPair(long jarg1, PropertyBlock jarg1_, long jarg2, PropertyPair jarg2_);
  public final static native long PropertyBlock_getPair(long jarg1, PropertyBlock jarg1_, long jarg2) throws java.lang.Exception;
  public final static native long PropertyBlock_size(long jarg1, PropertyBlock jarg1_);
  public final static native String PropertyBlock_getValue(long jarg1, PropertyBlock jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long new_CMMCore();
  public final static native void delete_CMMCore(long jarg1);
  public final static native void CMMCore_loadDevice(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4) throws java.lang.Exception;
  public final static native void CMMCore_unloadDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_unloadAllDevices(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_initializeAllDevices(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_initializeDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_updateCoreProperties(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_reset(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_clearLog(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_enableDebugLog(long jarg1, CMMCore jarg1_, boolean jarg2);
  public final static native boolean CMMCore_debugLogEnabled(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_enableStderrLog(long jarg1, CMMCore jarg1_, boolean jarg2);
  public final static native String CMMCore_getUserId(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getHostName(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_logMessage__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_logMessage__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, boolean jarg3);
  public final static native String CMMCore_saveLogArchive(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_saveLogArchiveWithPreamble(long jarg1, CMMCore jarg1_, String jarg2, int jarg3);
  public final static native String CMMCore_getVersionInfo(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getAPIVersionInfo(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getSystemState(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getSystemStateCache(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_updateSystemStateCache(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setSystemState(long jarg1, CMMCore jarg1_, long jarg2, Configuration jarg2_);
  public final static native long CMMCore_getConfigState(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native long CMMCore_getConfigGroupState(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getConfigGroupStateFromCache(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_saveSystemState(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadSystemState(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_saveSystemConfiguration(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadSystemConfiguration(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_registerCallback(long jarg1, CMMCore jarg1_, long jarg2, MMEventCallback jarg2_);
  public final static native long CMMCore_getAvailableDevices(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getAvailableDeviceDescriptions(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getAvailableDeviceTypes(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_addSearchPath(String jarg1);
  public final static native long CMMCore_getDeviceLibraries() throws java.lang.Exception;
  public final static native long CMMCore_getLoadedDevices(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getLoadedDevicesOfType(long jarg1, CMMCore jarg1_, int jarg2);
  public final static native long CMMCore_getDevicePropertyNames(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getProperty(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native String CMMCore_getPropertyFromCache(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setProperty__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setProperty__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, boolean jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setProperty__SWIG_2(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, int jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setProperty__SWIG_3(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, float jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setProperty__SWIG_4(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, double jarg4) throws java.lang.Exception;
  public final static native boolean CMMCore_hasProperty(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native long CMMCore_getAllowedPropertyValues(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_isPropertyReadOnly(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_isPropertyPreInit(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_isPropertySequenceable(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_hasPropertyLimits(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native double CMMCore_getPropertyLowerLimit(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native double CMMCore_getPropertyUpperLimit(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_startPropertySequence(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_stopPropertySequence(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native int CMMCore_getPropertySequenceMaxLength(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_loadPropertySequence(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, long jarg4, StrVector jarg4_) throws java.lang.Exception;
  public final static native int CMMCore_getPropertyType(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native int CMMCore_getDeviceType(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getDeviceLibrary(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_unloadLibrary(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getDeviceName(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getParentLabel(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setParentLabel(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native String CMMCore_getDeviceDescription(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native boolean CMMCore_deviceBusy(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_waitForDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_waitForConfig(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_systemBusy(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_waitForSystem(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_waitForImageSynchro(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native boolean CMMCore_deviceTypeBusy(long jarg1, CMMCore jarg1_, int jarg2) throws java.lang.Exception;
  public final static native void CMMCore_waitForDeviceType(long jarg1, CMMCore jarg1_, int jarg2) throws java.lang.Exception;
  public final static native void CMMCore_sleep(long jarg1, CMMCore jarg1_, double jarg2);
  public final static native double CMMCore_getDeviceDelayMs(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setDeviceDelayMs(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setTimeoutMs(long jarg1, CMMCore jarg1_, int jarg2);
  public final static native int CMMCore_getTimeoutMs(long jarg1, CMMCore jarg1_);
  public final static native boolean CMMCore_usesDeviceDelay(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getCoreErrorText(long jarg1, CMMCore jarg1_, int jarg2);
  public final static native String CMMCore_getCameraDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getShutterDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getFocusDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getXYStageDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getAutoFocusDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getImageProcessorDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getSLMDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getGalvoDevice(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getChannelGroup(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setCameraDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setShutterDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setFocusDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setXYStageDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setAutoFocusDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setImageProcessorDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setSLMDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setGalvoDevice(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setChannelGroup(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_defineConfig__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_defineConfig__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6) throws java.lang.Exception;
  public final static native void CMMCore_defineConfigGroup(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_deleteConfigGroup(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_renameConfigGroup(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native boolean CMMCore_isGroupDefined(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native boolean CMMCore_isConfigDefined(long jarg1, CMMCore jarg1_, String jarg2, String jarg3);
  public final static native void CMMCore_setConfig(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_deleteConfig__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_deleteConfig__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4, String jarg5) throws java.lang.Exception;
  public final static native void CMMCore_renameConfig(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4) throws java.lang.Exception;
  public final static native long CMMCore_getAvailableConfigGroups(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getAvailableConfigs(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native String CMMCore_getCurrentConfig(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getCurrentConfigFromCache(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getConfigData(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native String CMMCore_getCurrentPixelSizeConfig__SWIG_0(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native String CMMCore_getCurrentPixelSizeConfig__SWIG_1(long jarg1, CMMCore jarg1_, boolean jarg2) throws java.lang.Exception;
  public final static native double CMMCore_getPixelSizeUm__SWIG_0(long jarg1, CMMCore jarg1_);
  public final static native double CMMCore_getPixelSizeUm__SWIG_1(long jarg1, CMMCore jarg1_, boolean jarg2);
  public final static native double CMMCore_getPixelSizeUmByID(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native double CMMCore_getMagnificationFactor(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setPixelSizeUm(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native void CMMCore_definePixelSizeConfig__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native void CMMCore_definePixelSizeConfig__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getAvailablePixelSizeConfigs(long jarg1, CMMCore jarg1_);
  public final static native boolean CMMCore_isPixelSizeConfigDefined(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_setPixelSizeConfig(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_renamePixelSizeConfig(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_deletePixelSizeConfig(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getPixelSizeConfigData(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setROI(long jarg1, CMMCore jarg1_, int jarg2, int jarg3, int jarg4, int jarg5) throws java.lang.Exception;
  public final static native void CMMCore_getROI(long jarg1, CMMCore jarg1_, int[] jarg2, int[] jarg3, int[] jarg4, int[] jarg5) throws java.lang.Exception;
  public final static native void CMMCore_clearROI(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_setExposure__SWIG_0(long jarg1, CMMCore jarg1_, double jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setExposure__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native double CMMCore_getExposure(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native Object CMMCore_getImage__SWIG_0(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native Object CMMCore_getImage__SWIG_1(long jarg1, CMMCore jarg1_, long jarg2) throws java.lang.Exception;
  public final static native void CMMCore_snapImage(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native long CMMCore_getImageWidth(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getImageHeight(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getBytesPerPixel(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getImageBitDepth(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getNumberOfComponents(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getNumberOfCameraChannels(long jarg1, CMMCore jarg1_);
  public final static native String CMMCore_getCameraChannelName(long jarg1, CMMCore jarg1_, long jarg2);
  public final static native int CMMCore_getImageBufferSize(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_assignImageSynchro(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_removeImageSynchro(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_removeImageSynchroAll(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setAutoShutter(long jarg1, CMMCore jarg1_, boolean jarg2);
  public final static native boolean CMMCore_getAutoShutter(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setShutterOpen(long jarg1, CMMCore jarg1_, boolean jarg2) throws java.lang.Exception;
  public final static native boolean CMMCore_getShutterOpen(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_startSequenceAcquisition__SWIG_0(long jarg1, CMMCore jarg1_, int jarg2, double jarg3, boolean jarg4) throws java.lang.Exception;
  public final static native void CMMCore_startSequenceAcquisition__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, int jarg3, double jarg4, boolean jarg5) throws java.lang.Exception;
  public final static native void CMMCore_prepareSequenceAcquisition(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_startContinuousSequenceAcquisition(long jarg1, CMMCore jarg1_, double jarg2) throws java.lang.Exception;
  public final static native void CMMCore_stopSequenceAcquisition__SWIG_0(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_stopSequenceAcquisition__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native boolean CMMCore_isSequenceRunning__SWIG_0(long jarg1, CMMCore jarg1_);
  public final static native boolean CMMCore_isSequenceRunning__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native Object CMMCore_getLastImage(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native Object CMMCore_popNextImage(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native Object CMMCore_getLastImageMD__SWIG_0(long jarg1, CMMCore jarg1_, long jarg2, long jarg3, long jarg4, Metadata jarg4_) throws java.lang.Exception;
  public final static native Object CMMCore_popNextImageMD__SWIG_0(long jarg1, CMMCore jarg1_, long jarg2, long jarg3, long jarg4, Metadata jarg4_) throws java.lang.Exception;
  public final static native Object CMMCore_getLastImageMD__SWIG_1(long jarg1, CMMCore jarg1_, long jarg2, Metadata jarg2_) throws java.lang.Exception;
  public final static native Object CMMCore_getNBeforeLastImageMD(long jarg1, CMMCore jarg1_, long jarg2, long jarg3, Metadata jarg3_) throws java.lang.Exception;
  public final static native Object CMMCore_popNextImageMD__SWIG_1(long jarg1, CMMCore jarg1_, long jarg2, Metadata jarg2_) throws java.lang.Exception;
  public final static native int CMMCore_getRemainingImageCount(long jarg1, CMMCore jarg1_);
  public final static native int CMMCore_getBufferTotalCapacity(long jarg1, CMMCore jarg1_);
  public final static native int CMMCore_getBufferFreeCapacity(long jarg1, CMMCore jarg1_);
  public final static native double CMMCore_getBufferIntervalMs(long jarg1, CMMCore jarg1_);
  public final static native boolean CMMCore_isBufferOverflowed(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_setCircularBufferMemoryFootprint(long jarg1, CMMCore jarg1_, long jarg2) throws java.lang.Exception;
  public final static native void CMMCore_initializeCircularBuffer(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_clearCircularBuffer(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native boolean CMMCore_isExposureSequenceable(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_startExposureSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_stopExposureSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native int CMMCore_getExposureSequenceMaxLength(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadExposureSequence(long jarg1, CMMCore jarg1_, String jarg2, long jarg3, DoubleVector jarg3_) throws java.lang.Exception;
  public final static native double CMMCore_getLastFocusScore(long jarg1, CMMCore jarg1_);
  public final static native double CMMCore_getCurrentFocusScore(long jarg1, CMMCore jarg1_);
  public final static native void CMMCore_enableContinuousFocus(long jarg1, CMMCore jarg1_, boolean jarg2) throws java.lang.Exception;
  public final static native boolean CMMCore_isContinuousFocusEnabled(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native boolean CMMCore_isContinuousFocusLocked(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native boolean CMMCore_isContinuousFocusDrive(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_fullFocus(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_incrementalFocus(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_setAutoFocusOffset(long jarg1, CMMCore jarg1_, double jarg2) throws java.lang.Exception;
  public final static native double CMMCore_getAutoFocusOffset(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_setState(long jarg1, CMMCore jarg1_, String jarg2, int jarg3) throws java.lang.Exception;
  public final static native int CMMCore_getState(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native int CMMCore_getNumberOfStates(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_setStateLabel(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native String CMMCore_getStateLabel(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_defineStateLabel(long jarg1, CMMCore jarg1_, String jarg2, int jarg3, String jarg4) throws java.lang.Exception;
  public final static native long CMMCore_getStateLabels(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native int CMMCore_getStateFromLabel(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native long CMMCore_getStateLabelData(long jarg1, CMMCore jarg1_, String jarg2, String jarg3);
  public final static native long CMMCore_getData(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_definePropertyBlock(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long CMMCore_getAvailablePropertyBlocks(long jarg1, CMMCore jarg1_);
  public final static native long CMMCore_getPropertyBlockData(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_setPosition(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native double CMMCore_getPosition(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setRelativePosition(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setOrigin(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setAdapterOrigin(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setXYPosition(long jarg1, CMMCore jarg1_, String jarg2, double jarg3, double jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setRelativeXYPosition(long jarg1, CMMCore jarg1_, String jarg2, double jarg3, double jarg4) throws java.lang.Exception;
  public final static native void CMMCore_getXYPosition(long jarg1, CMMCore jarg1_, String jarg2, double[] jarg3, double[] jarg4) throws java.lang.Exception;
  public final static native double CMMCore_getXPosition(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native double CMMCore_getYPosition(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_stop(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_home(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setOriginXY(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setAdapterOriginXY(long jarg1, CMMCore jarg1_, String jarg2, double jarg3, double jarg4) throws java.lang.Exception;
  public final static native boolean CMMCore_isStageSequenceable(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_startStageSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_stopStageSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native int CMMCore_getStageSequenceMaxLength(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadStageSequence(long jarg1, CMMCore jarg1_, String jarg2, long jarg3, DoubleVector jarg3_) throws java.lang.Exception;
  public final static native boolean CMMCore_isXYStageSequenceable(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_startXYStageSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_stopXYStageSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native int CMMCore_getXYStageSequenceMaxLength(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadXYStageSequence(long jarg1, CMMCore jarg1_, String jarg2, long jarg3, DoubleVector jarg3_, long jarg4, DoubleVector jarg4_) throws java.lang.Exception;
  public final static native void CMMCore_setSerialProperties(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8) throws java.lang.Exception;
  public final static native void CMMCore_setSerialPortCommand(long jarg1, CMMCore jarg1_, String jarg2, String jarg3, String jarg4) throws java.lang.Exception;
  public final static native String CMMCore_getSerialPortAnswer(long jarg1, CMMCore jarg1_, String jarg2, String jarg3) throws java.lang.Exception;
  public final static native void CMMCore_writeToSerialPort(long jarg1, CMMCore jarg1_, String jarg2, long jarg3, CharVector jarg3_) throws java.lang.Exception;
  public final static native long CMMCore_readFromSerialPort(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setSLMImage__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, byte[] jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setSLMImage__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, int[] jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setSLMPixelsTo__SWIG_0(long jarg1, CMMCore jarg1_, String jarg2, short jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setSLMPixelsTo__SWIG_1(long jarg1, CMMCore jarg1_, String jarg2, short jarg3, short jarg4, short jarg5) throws java.lang.Exception;
  public final static native void CMMCore_displaySLMImage(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long CMMCore_getSLMWidth(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getSLMHeight(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getSLMNumberOfComponents(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getSLMBytesPerPixel(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native void CMMCore_pointGalvoAndFire(long jarg1, CMMCore jarg1_, String jarg2, double jarg3, double jarg4, double jarg5) throws java.lang.Exception;
  public final static native void CMMCore_setGalvoSpotInterval(long jarg1, CMMCore jarg1_, String jarg2, double jarg3) throws java.lang.Exception;
  public final static native void CMMCore_setGalvoPosition(long jarg1, CMMCore jarg1_, String jarg2, double jarg3, double jarg4) throws java.lang.Exception;
  public final static native void CMMCore_getGalvoPosition(long jarg1, CMMCore jarg1_, String jarg2, double[] jarg3, double[] jarg4) throws java.lang.Exception;
  public final static native void CMMCore_setGalvoIlluminationState(long jarg1, CMMCore jarg1_, String jarg2, boolean jarg3) throws java.lang.Exception;
  public final static native double CMMCore_getGalvoXRange(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native double CMMCore_getGalvoYRange(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_addGalvoPolygonVertex(long jarg1, CMMCore jarg1_, String jarg2, int jarg3, double jarg4, double jarg5) throws java.lang.Exception;
  public final static native void CMMCore_deleteGalvoPolygons(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_loadGalvoPolygons(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_setGalvoPolygonRepetitions(long jarg1, CMMCore jarg1_, String jarg2, int jarg3) throws java.lang.Exception;
  public final static native void CMMCore_runGalvoPolygons(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_runGalvoSequence(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native String CMMCore_getGalvoChannel(long jarg1, CMMCore jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void CMMCore_acqBeforeFrame(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native void CMMCore_acqAfterFrame(long jarg1, CMMCore jarg1_) throws java.lang.Exception;
  public final static native int CMMCore_detectDevice(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getInstalledDevices(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native String CMMCore_getInstalledDeviceDescription(long jarg1, CMMCore jarg1_, String jarg2, String jarg3);
  public final static native long CMMCore_getLoadedPeripheralDevices(long jarg1, CMMCore jarg1_, String jarg2);
  public final static native long CMMCore_getMACAddresses(long jarg1, CMMCore jarg1_);
  public final static native long new_MetadataError(String jarg1);
  public final static native void delete_MetadataError(long jarg1);
  public final static native String MetadataError_getMsg(long jarg1, MetadataError jarg1_);
  public final static native long new_MetadataKeyError();
  public final static native void delete_MetadataKeyError(long jarg1);
  public final static native long new_MetadataIndexError();
  public final static native void delete_MetadataIndexError(long jarg1);
  public final static native void delete_MetadataTag(long jarg1);
  public final static native String MetadataTag_GetDevice(long jarg1, MetadataTag jarg1_);
  public final static native String MetadataTag_GetName(long jarg1, MetadataTag jarg1_);
  public final static native String MetadataTag_GetQualifiedName(long jarg1, MetadataTag jarg1_);
  public final static native boolean MetadataTag_IsReadOnly(long jarg1, MetadataTag jarg1_);
  public final static native void MetadataTag_SetDevice(long jarg1, MetadataTag jarg1_, String jarg2);
  public final static native void MetadataTag_SetName(long jarg1, MetadataTag jarg1_, String jarg2);
  public final static native void MetadataTag_SetReadOnly(long jarg1, MetadataTag jarg1_, boolean jarg2);
  public final static native long MetadataTag_ToSingleTag(long jarg1, MetadataTag jarg1_);
  public final static native long MetadataTag_ToArrayTag(long jarg1, MetadataTag jarg1_);
  public final static native long MetadataTag_Clone(long jarg1, MetadataTag jarg1_);
  public final static native String MetadataTag_Serialize(long jarg1, MetadataTag jarg1_);
  public final static native boolean MetadataTag_Restore(long jarg1, MetadataTag jarg1_, String jarg2);
  public final static native long new_MetadataSingleTag__SWIG_0();
  public final static native long new_MetadataSingleTag__SWIG_1(String jarg1, String jarg2, boolean jarg3);
  public final static native void delete_MetadataSingleTag(long jarg1);
  public final static native String MetadataSingleTag_GetValue(long jarg1, MetadataSingleTag jarg1_);
  public final static native void MetadataSingleTag_SetValue(long jarg1, MetadataSingleTag jarg1_, String jarg2);
  public final static native long MetadataSingleTag_ToSingleTag(long jarg1, MetadataSingleTag jarg1_);
  public final static native long MetadataSingleTag_Clone(long jarg1, MetadataSingleTag jarg1_);
  public final static native String MetadataSingleTag_Serialize(long jarg1, MetadataSingleTag jarg1_);
  public final static native boolean MetadataSingleTag_Restore(long jarg1, MetadataSingleTag jarg1_, String jarg2);
  public final static native long new_MetadataArrayTag();
  public final static native void delete_MetadataArrayTag(long jarg1);
  public final static native long MetadataArrayTag_ToArrayTag(long jarg1, MetadataArrayTag jarg1_);
  public final static native void MetadataArrayTag_AddValue(long jarg1, MetadataArrayTag jarg1_, String jarg2);
  public final static native void MetadataArrayTag_SetValue(long jarg1, MetadataArrayTag jarg1_, String jarg2, long jarg3);
  public final static native String MetadataArrayTag_GetValue(long jarg1, MetadataArrayTag jarg1_, long jarg2);
  public final static native long MetadataArrayTag_GetSize(long jarg1, MetadataArrayTag jarg1_);
  public final static native long MetadataArrayTag_Clone(long jarg1, MetadataArrayTag jarg1_);
  public final static native String MetadataArrayTag_Serialize(long jarg1, MetadataArrayTag jarg1_);
  public final static native boolean MetadataArrayTag_Restore(long jarg1, MetadataArrayTag jarg1_, String jarg2);
  public final static native long new_Metadata__SWIG_0();
  public final static native void delete_Metadata(long jarg1);
  public final static native long new_Metadata__SWIG_1(long jarg1, Metadata jarg1_);
  public final static native void Metadata_Clear(long jarg1, Metadata jarg1_);
  public final static native long Metadata_GetKeys(long jarg1, Metadata jarg1_);
  public final static native boolean Metadata_HasTag(long jarg1, Metadata jarg1_, String jarg2);
  public final static native long Metadata_GetSingleTag(long jarg1, Metadata jarg1_, String jarg2) throws java.lang.Exception;
  public final static native long Metadata_GetArrayTag(long jarg1, Metadata jarg1_, String jarg2) throws java.lang.Exception;
  public final static native void Metadata_SetTag(long jarg1, Metadata jarg1_, long jarg2, MetadataTag jarg2_);
  public final static native void Metadata_RemoveTag(long jarg1, Metadata jarg1_, String jarg2);
  public final static native long Metadata_eql(long jarg1, Metadata jarg1_, long jarg2, Metadata jarg2_);
  public final static native void Metadata_Merge(long jarg1, Metadata jarg1_, long jarg2, Metadata jarg2_);
  public final static native String Metadata_Serialize(long jarg1, Metadata jarg1_);
  public final static native String Metadata_readLine(long jarg1, Metadata jarg1_, long jarg2);
  public final static native boolean Metadata_Restore(long jarg1, Metadata jarg1_, String jarg2);
  public final static native String Metadata_Dump(long jarg1, Metadata jarg1_);
  public final static native long new_MMEventCallback();
  public final static native void delete_MMEventCallback(long jarg1);
  public final static native void MMEventCallback_onPropertiesChanged(long jarg1, MMEventCallback jarg1_);
  public final static native void MMEventCallback_onPropertiesChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_);
  public final static native void MMEventCallback_onPropertyChanged(long jarg1, MMEventCallback jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void MMEventCallback_onPropertyChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void MMEventCallback_onConfigGroupChanged(long jarg1, MMEventCallback jarg1_, String jarg2, String jarg3);
  public final static native void MMEventCallback_onConfigGroupChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, String jarg3);
  public final static native void MMEventCallback_onPixelSizeChanged(long jarg1, MMEventCallback jarg1_, double jarg2);
  public final static native void MMEventCallback_onPixelSizeChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, double jarg2);
  public final static native void MMEventCallback_onStagePositionChanged(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_onStagePositionChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_onStagePositionChangedRelative(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_onStagePositionChangedRelativeSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_onXYStagePositionChanged(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3, double jarg4);
  public final static native void MMEventCallback_onXYStagePositionChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3, double jarg4);
  public final static native void MMEventCallback_onXYStagePositionChangedRelative(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3, double jarg4);
  public final static native void MMEventCallback_onXYStagePositionChangedRelativeSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3, double jarg4);
  public final static native void MMEventCallback_onExposureChanged(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_onExposureChangedSwigExplicitMMEventCallback(long jarg1, MMEventCallback jarg1_, String jarg2, double jarg3);
  public final static native void MMEventCallback_director_connect(MMEventCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MMEventCallback_change_ownership(MMEventCallback obj, long cptr, boolean take_or_release);
  public final static native long MetadataKeyError_SWIGUpcast(long jarg1);
  public final static native long MetadataIndexError_SWIGUpcast(long jarg1);
  public final static native long MetadataSingleTag_SWIGUpcast(long jarg1);
  public final static native long MetadataArrayTag_SWIGUpcast(long jarg1);

  public static void SwigDirector_MMEventCallback_onPropertiesChanged(MMEventCallback self) {
    self.onPropertiesChanged();
  }
  public static void SwigDirector_MMEventCallback_onPropertyChanged(MMEventCallback self, String name, String propName, String propValue) {
    self.onPropertyChanged(name, propName, propValue);
  }
  public static void SwigDirector_MMEventCallback_onConfigGroupChanged(MMEventCallback self, String groupName, String newConfigName) {
    self.onConfigGroupChanged(groupName, newConfigName);
  }
  public static void SwigDirector_MMEventCallback_onPixelSizeChanged(MMEventCallback self, double newPixelSizeUm) {
    self.onPixelSizeChanged(newPixelSizeUm);
  }
  public static void SwigDirector_MMEventCallback_onStagePositionChanged(MMEventCallback self, String name, double pos) {
    self.onStagePositionChanged(name, pos);
  }
  public static void SwigDirector_MMEventCallback_onStagePositionChangedRelative(MMEventCallback self, String name, double pos) {
    self.onStagePositionChangedRelative(name, pos);
  }
  public static void SwigDirector_MMEventCallback_onXYStagePositionChanged(MMEventCallback self, String name, double xpos, double ypos) {
    self.onXYStagePositionChanged(name, xpos, ypos);
  }
  public static void SwigDirector_MMEventCallback_onXYStagePositionChangedRelative(MMEventCallback self, String name, double xpos, double ypos) {
    self.onXYStagePositionChangedRelative(name, xpos, ypos);
  }
  public static void SwigDirector_MMEventCallback_onExposureChanged(MMEventCallback self, String name, double newExposure) {
    self.onExposureChanged(name, newExposure);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
