/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class pair_ss {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pair_ss(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pair_ss obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_pair_ss(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public pair_ss() {
    this(MMCoreJJNI.new_pair_ss__SWIG_0(), true);
  }

  public pair_ss(String first, String second) {
    this(MMCoreJJNI.new_pair_ss__SWIG_1(first, second), true);
  }

  public pair_ss(pair_ss p) {
    this(MMCoreJJNI.new_pair_ss__SWIG_2(pair_ss.getCPtr(p), p), true);
  }

  public void setFirst(String value) {
    MMCoreJJNI.pair_ss_first_set(swigCPtr, this, value);
  }

  public String getFirst() {
    return MMCoreJJNI.pair_ss_first_get(swigCPtr, this);
  }

  public void setSecond(String value) {
    MMCoreJJNI.pair_ss_second_set(swigCPtr, this, value);
  }

  public String getSecond() {
    return MMCoreJJNI.pair_ss_second_get(swigCPtr, this);
  }

}
