/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class PropertyPair {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PropertyPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PropertyPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_PropertyPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PropertyPair(String prop, String value) {
    this(MMCoreJJNI.new_PropertyPair__SWIG_0(prop, value), true);
  }

  public PropertyPair() {
    this(MMCoreJJNI.new_PropertyPair__SWIG_1(), true);
  }

  public String getPropertyName() {
    return MMCoreJJNI.PropertyPair_getPropertyName(swigCPtr, this);
  }

  public String getPropertyValue() {
    return MMCoreJJNI.PropertyPair_getPropertyValue(swigCPtr, this);
  }

}
