/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mmcorej;

public class StrMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StrMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MMCoreJJNI.delete_StrMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StrMap() {
    this(MMCoreJJNI.new_StrMap__SWIG_0(), true);
  }

  public StrMap(StrMap arg0) {
    this(MMCoreJJNI.new_StrMap__SWIG_1(StrMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return MMCoreJJNI.StrMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return MMCoreJJNI.StrMap_empty(swigCPtr, this);
  }

  public void clear() {
    MMCoreJJNI.StrMap_clear(swigCPtr, this);
  }

  public String get(String key) {
    return MMCoreJJNI.StrMap_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    MMCoreJJNI.StrMap_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    MMCoreJJNI.StrMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return MMCoreJJNI.StrMap_has_key(swigCPtr, this, key);
  }

}
